<a href="https://colab.research.google.com/github/Khadija-Azam05/ML-Projects/blob/main/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Khadija-Azam05/ML-Projects/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [ ]:
!pip install -q datasets huggingface_hub

In [ ]:
from huggingface_hub import notebook_login

notebook_login()

In [ ]:
!pip install -q datasets

In [ ]:
from datasets import load_dataset

dataset = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_query_90d"
)

fact_content_query_90d.parquet: reconstructing file:   0%|          |  0.00B / 60.7MB

fact_content_query_90d.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/2414248 [00:00<?, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['client_hash_id', 'content_hash_id', 'query_hash_id', 'query_char_count', 'query_token_count', 'window_start', 'window_end', 'impressions_90d', 'clicks_90d', 'impressions_last30', 'clicks_last30', 'impressions_prev30', 'clicks_prev30', 'avg_position_90d', 'avg_position_last30', 'avg_position_prev30', 'content_total_impressions_90d', 'content_visible_query_count', 'rare_query_count', 'rare_impressions_share', 'anonymized_impressions_share'],
        num_rows: 2414248
    })
})

In [ ]:
df = dataset["train"].to_pandas()

df.head()

,client_hash_id,content_hash_id,query_hash_id,query_char_count,query_token_count,window_start,window_end,impressions_90d,clicks_90d,impressions_last30,...,impressions_prev30,clicks_prev30,avg_position_90d,avg_position_last30,avg_position_prev30,content_total_impressions_90d,content_visible_query_count,rare_query_count,rare_impressions_share,anonymized_impressions_share
0,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_58b1b001f839d699,17,3,2026-04-02,2026-06-30,11,0,0,...,11,0,10.818182,NaN,10.818182,1466,14,32,0.043656,0.725102
1,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_922b8eca2a24cd34,34,7,2026-04-02,2026-06-30,13,0,0,...,1,0,1.769231,NaN,11.000000,1466,14,32,0.043656,0.725102
2,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_9f0c36a6ae2a6a99,16,2,2026-04-02,2026-06-30,16,0,11,...,5,0,23.562500,24.272727,22.000000,1466,14,32,0.043656,0.725102
3,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_a032820b5467e996,24,4,2026-04-02,2026-06-30,55,0,1,...,1,0,2.200000,13.000000,0.000000,1466,14,32,0.043656,0.725102
4,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_ba1a2f131961c5da,18,3,2026-04-02,2026-06-30,14,0,0,...,0,0,3.428571,NaN,NaN,1466,14,32,0.043656,0.725102

In [ ]:
df = dataset["train"].to_pandas()

In [ ]:
df.head()

,client_hash_id,content_hash_id,query_hash_id,query_char_count,query_token_count,window_start,window_end,impressions_90d,clicks_90d,impressions_last30,...,impressions_prev30,clicks_prev30,avg_position_90d,avg_position_last30,avg_position_prev30,content_total_impressions_90d,content_visible_query_count,rare_query_count,rare_impressions_share,anonymized_impressions_share
0,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_58b1b001f839d699,17,3,2026-04-02,2026-06-30,11,0,0,...,11,0,10.818182,NaN,10.818182,1466,14,32,0.043656,0.725102
1,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_922b8eca2a24cd34,34,7,2026-04-02,2026-06-30,13,0,0,...,1,0,1.769231,NaN,11.000000,1466,14,32,0.043656,0.725102
2,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_9f0c36a6ae2a6a99,16,2,2026-04-02,2026-06-30,16,0,11,...,5,0,23.562500,24.272727,22.000000,1466,14,32,0.043656,0.725102
3,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_a032820b5467e996,24,4,2026-04-02,2026-06-30,55,0,1,...,1,0,2.200000,13.000000,0.000000,1466,14,32,0.043656,0.725102
4,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_ba1a2f131961c5da,18,3,2026-04-02,2026-06-30,14,0,0,...,0,0,3.428571,NaN,NaN,1466,14,32,0.043656,0.725102

In [ ]:
df.shape

(2414248, 21)

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

## My lane as an ML task (type)

**Task Type:** Ranking

I am framing my lane as a **ranking** task because the goal is to prioritize content pages that should be reviewed first. Instead of predicting only "review" or "do not review," the model ranks content based on search performance signals so the SEO or content team can focus on the highest-priority pages first.

In [ ]:
print("ML Task Type: Ranking")

ML Task Type: Ranking

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

## Target or Proxy

The dataset does not contain a direct label indicating whether content should be refreshed. Therefore, I would use a **proxy target** based on observed search performance. Pages or content-query pairs with low clicks, declining visibility, poor average position, or low impression share could be assigned a higher refresh priority. This proxy is derived from observed data rather than a manually labeled outcome.

In [ ]:
df[[
    "impressions_90d",
    "clicks_90d",
    "avg_position_90d",
    "content_total_impressions_90d"
]].head()

,impressions_90d,clicks_90d,avg_position_90d,content_total_impressions_90d
0,11,0,10.818182,1466
1,13,0,1.769231,1466
2,16,0,23.562500,1466
3,55,0,2.200000,1466
4,14,0,3.428571,1466

## 3. Success metric

*One metric you can defend. What number means 'good'?*

## Success Metric

The success of this task will be measured by how well the model ranks high-priority content near the top of the list. A good model helps the content team quickly identify which pages should be reviewed first, reducing the time spent reviewing lower-priority pages. The ranking should consistently place the most valuable refresh opportunities near the top.

In [ ]:
df[["impressions_90d", "clicks_90d", "avg_position_90d"]].describe()

       impressions_90d    clicks_90d  avg_position_90d
count     2.414248e+06  2.414248e+06      2.414248e+06
mean      8.770558e+01  1.905016e-01      1.976747e+01
std       9.332719e+02  1.940454e+00      2.394363e+01
min       1.000000e+01  0.000000e+00      0.000000e+00
25%       1.400000e+01  0.000000e+00      4.960000e+00
50%       2.300000e+01  0.000000e+00      8.782609e+00
75%       5.200000e+01  0.000000e+00      2.666667e+01
max       5.430440e+05  1.109000e+03      4.327500e+02

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

## The unit of analysis

One row represents the performance of a single **content-query pair** over a 90-day time window. Each row contains search performance metrics, such as impressions, clicks, average search position, and other aggregated features. The model uses these observations to rank which content may deserve review first.

In [ ]:
print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (2414248, 21)

,client_hash_id,content_hash_id,query_hash_id,query_char_count,query_token_count,window_start,window_end,impressions_90d,clicks_90d,impressions_last30,...,impressions_prev30,clicks_prev30,avg_position_90d,avg_position_last30,avg_position_prev30,content_total_impressions_90d,content_visible_query_count,rare_query_count,rare_impressions_share,anonymized_impressions_share
0,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_58b1b001f839d699,17,3,2026-04-02,2026-06-30,11,0,0,...,11,0,10.818182,NaN,10.818182,1466,14,32,0.043656,0.725102
1,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_922b8eca2a24cd34,34,7,2026-04-02,2026-06-30,13,0,0,...,1,0,1.769231,NaN,11.000000,1466,14,32,0.043656,0.725102
2,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_9f0c36a6ae2a6a99,16,2,2026-04-02,2026-06-30,16,0,11,...,5,0,23.562500,24.272727,22.000000,1466,14,32,0.043656,0.725102
3,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_a032820b5467e996,24,4,2026-04-02,2026-06-30,55,0,1,...,1,0,2.200000,13.000000,0.000000,1466,14,32,0.043656,0.725102
4,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_ba1a2f131961c5da,18,3,2026-04-02,2026-06-30,14,0,0,...,0,0,3.428571,NaN,NaN,1466,14,32,0.043656,0.725102

In [ ]:
df[[
    "content_hash_id",
    "query_hash_id",
    "impressions_90d",
    "clicks_90d",
    "avg_position_90d"
]].head()

,content_hash_id,query_hash_id,impressions_90d,clicks_90d,avg_position_90d
0,content_447894f2faf0d2bc,query_58b1b001f839d699,11,0,10.818182
1,content_447894f2faf0d2bc,query_922b8eca2a24cd34,13,0,1.769231
2,content_447894f2faf0d2bc,query_9f0c36a6ae2a6a99,16,0,23.562500
3,content_447894f2faf0d2bc,query_a032820b5467e996,55,0,2.200000
4,content_447894f2faf0d2bc,query_ba1a2f131961c5da,14,0,3.428571

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

## Why ML beats a fixed rule here

A fixed rule cannot capture the complex relationships between search performance metrics. For example, a page with low clicks may still perform well if it has low search volume, while another page with similar clicks but many impressions may need attention. Machine learning can learn patterns from multiple features, such as impressions, clicks, average position, query visibility, and content performance, to produce a better ranking than a single threshold-based rule.

In [ ]:
# Explore relationships between important features
df[[
    "impressions_90d",
    "clicks_90d",
    "avg_position_90d",
    "content_total_impressions_90d"
]].corr()

,impressions_90d,clicks_90d,avg_position_90d,content_total_impressions_90d
impressions_90d,1.000000,0.297717,-0.029779,0.026776
clicks_90d,0.297717,1.000000,-0.057522,0.035008
avg_position_90d,-0.029779,-0.057522,1.000000,-0.124890
content_total_impressions_90d,0.026776,0.035008,-0.124890,1.000000